Advanced_Django_CBV/advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from cbv_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.CBView.as_view(),
    path('', views.IndexView.as_view()),
    path('cbv_app/', include('cbv_app.urls', namespace='cbv_app'))
]

Advanced_Django_CBV/advcbv/cbv_app/urls.py
from django.urls import path, re_path
from cbv_app import views


app_name = 'cbv_app'

urlpatterns = [
  path('', views.SchoolListView.as_view(), name='list'),
  re_path(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
  path('create/', views.SchoolCreateView.as_view(), name='create'),
  # pk is same as re_path 2 above
  path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
  path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete')
]

Advanced_Django_CBV/advcbv/cbv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
  name = models.CharField(max_length=256)
  principal = models.CharField(max_length=256)
  location = models.CharField(max_length=256)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('cbv_app:detail', kwargs={'pk': self.pk})  

class Student(models.Model):
  name = models.CharField(max_length=256)
  age = models.PositiveIntegerField()
  school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

  def __str__(self):
    return self.name

Advanced_Django_CBV/advcbv/cbv_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from django.http import HttpResponse
from . import models

# Create your views here.
# def index(req):
#   return render(req, 'index.html')

# class CBView(View):
#   def get(self, req):
#     return HttpResponse('Class Based Views Here!')

class IndexView(TemplateView):
  template_name = 'index.html'

#   def get_context_data(self, **kwargs):
#     context = super().get_context_data(**kwargs)
#     context['injectme'] = 'I am INJECTED!'
#     return context

class SchoolListView(ListView):
  context_object_name = 'schools'
  model = models.School
  # returns 'school_list'
  # after contex_object_name var, it returns 'schools'

class SchoolDetailView(DetailView):
  context_object_name = 'school_detail'
  model = models.School
  template_name = 'cbv_app/school_detail.html'

class SchoolCreateView(CreateView):
  fields = ('name', 'principal', 'location')
  model = models.School

class SchoolUpdateView(UpdateView):
  fields = ('name', 'principal')
  model = models.School

class SchoolDeleteView(DeleteView):
  model = models.School
  success_url = reverse_lazy('cbv_app:list')

Advanced_Django_CBV/advcbv/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html>
<head>
  <title>Base</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">SCHOOLS</a></li>
      <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a class="nav-link" href="#"></a></li>
    </ul>
  </nav>

  <div class="container">
    {% block body_block %}
        
    {% endblock body_block %}
  </div>

</body>
</html>

Advanced_Django_CBV/advcbv/cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}

<div class="jumbotron">    
  <h1>Are you fucking serious?! You're gonna delete the <b color="red">{{ school.name }}</b> man?</h1>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" name="delete" class="btn btn-danger" value="Delete">
    <a href="{% url 'cbv_app:detail' pk=school.pk %}">Cancel</a>
  </form>
</div>

{% endblock body_block %}

Advanced_Django_CBV/advcbv/cbv_app/templates/cbv_app/school_detail.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}
    
<div class="jumbotron">
  <h1>School Detail Page</h1>
  <h2>School details:</h2>
  <p>Name: {{ school_detail.name }}</p>
  <p>Principal: {{ school_detail.principal }}</p>
  <p>Location: {{ school_detail.location }}</p>
  
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old</p>
  {% endfor %}

  <p>
    <a class="btn btn-warning" href="{% url 'cbv_app:update' pk=school_detail.pk %}">UPDATE</a>
    <a class="btn btn-danger" href="{% url 'cbv_app:delete' pk=school_detail.pk %}">DELETE</a>
  </p>
</div>

{% endblock body_block %}

Advanced_Django_CBV/advcbv/cbv_app/templates/cbv_app/school_form.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}
    
<div class="jumbotron">
  <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School    
    {% endif %}
  </h1>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="btn" class="btn btn-primary" value="Submit">
  </form>
</div>

{% endblock body_block %}

Advanced_Django_CBV/advcbv/cbv_app/templates/cbv_app/school_list.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}
 
<div class="jumbotron">   
  <h1>List of all Schools</h1>
    <br>
    <ol>
      {% for school in schools %}
        <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
      {% endfor %}
    </ol>
    <br>
    <p><a class="btn btn-primary" href="{% url 'cbv_app:create' %}">Create Another</a></p>
</div>

{% endblock body_block %}

Advanced_Django_CBV/advcbv/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Base</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">SCHOOLS</a></li>
      <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a class="nav-link" href="#"></a></li>
    </ul>
  </nav>

  <div class="container">
    {% block body_block %}
        
    {% endblock body_block %}
  </div>

</body>
</html>

Advanced_Django_CBV/advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Index Page</h1>
  </div>
{% endblock body_block %}